version: "3"

services:
  magiconion:
    image: cysharp/magiconion_sample_chatapp:3.0.13
    ports:
      - 12345:12345
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MagicOnion__ServerPorts__0__Host=0.0.0.0
