# as wsl could not mount volume, no persistence
ingress:
  enabled: true
  hosts:
    - grafana.chatapp.magiconion.local

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.chatapp.svc.cluster.local
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    kube-cluster:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    magiconion-overview:
      gnetId: 10584
      revision: 9
      datasource: Prometheus

adminPassword: admin
