apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  labels:
    app: magiconion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magiconion
  template:
    metadata:
      labels:
        app: magiconion
    spec:
      containers:
        - name: chatapp
          image: cysharp/magiconion_sample_chatapp_telemetry:3.0.13
          ports:
            - containerPort: 12345
              name: magiconion
            - containerPort: 9184
              name: prometheus
