apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  labels:
    app: magiconion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magiconion
  template:
    metadata:
      labels:
        app: magiconion
    spec:
      containers:
        - name: chatapp
          image: cysharp/magiconion_sample_chatapp_telemetry:4.0.1-1.0.0.rc2
          ports:
            - containerPort: 80
              name: magiconion
            - containerPort: 9184
              name: prometheus
          env:
            - name: DOTNET_ENVIRONMENT
              value: Development
            - name: MagicOnion__OpenTelemetry__MetricsExporterEndpoint
              value: http://127.0.0.1:9184/metrics/
            - name: MagicOnion__OpenTelemetry__MetricsExporterHostingEndpoint
              value: http://+:9184/metrics/
            - name: UseExporter
              value: console
            - name: Jaeger__Host
              value: jaeger-agent
            - name: Zipkin__Endpoint
              value: http://zipkin:9411/api/v2/spans
