version: "3"

services:
  magiconion:
    image: cysharp/magiconion_sample_chatapp_telemetry:3.0.13
    ports:
      - 12345:12345
      - 9184:9184
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MagicOnion__ServerPorts__0__Host=0.0.0.0
      - MagicOnion__OpenTelemetry__MetricsExporterEndpoint=http://127.0.0.1:9184/metrics/
      - MagicOnion__OpenTelemetry__TracerExporterEndpoint=http://zipkin:9411/api/v2/spans
      - MagicOnion__OpenTelemetry__PrometheusMetricsHostingEndpoint=http://+:9184/metrics/
