name: Setup .NET SDKs
runs:
  using: "composite"
  steps:
    - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
    - name: "Prepare Environment Variables (.NET SDK)"
      shell: bash
      run: |
          echo "MSBUILDDISABLENODEREUSE=1" | tee -a "$GITHUB_ENV"
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" | tee -a "$GITHUB_ENV"
          echo "DOTNET_NOLOGO=1" | tee -a "$GITHUB_ENV"
          echo "COMPlus_EnableDiagnostics=0" | tee -a "$GITHUB_ENV"
          echo "NUGET_XMLDOC_MODE=skip" | tee -a "$GITHUB_ENV"
