name: Benchmark

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      reuse:
        description: "reuse: Reuse existing benchmark server if possible"
        required: false
        default: true
        type: boolean
      benchmark-config-name:
        description: "benchmark-config-name: Select benchmark config name"
        required: false
        default: workflow_dispatch_messagepack_h2c
        type: choice
        options:
          - workflow_dispatch_memorypack_h2
          - workflow_dispatch_memorypack_h2c
          - workflow_dispatch_memorypack_h3
          - workflow_dispatch_messagepack_h2
          - workflow_dispatch_messagepack_h2c
          - workflow_dispatch_messagepack_h3
          - issue
          - schedule

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  benchmark:
    uses: Cysharp/Actions/.github/workflows/benchmark-execute.yaml@main
    with:
      benchmark-name: "magiconion-${{ github.event.issue.number || (inputs.reuse && 'wf' || github.run_number) }}"
      benchmark-config-path: "perf/BenchmarkApp/configs/${{ inputs.benchmark-config-name || github.event_name }}.yaml"
    secrets: inherit

  cleanup-failed:
    if: ${{ always() }}
    needs: [benchmark]
    uses: Cysharp/Actions/.github/workflows/benchmark-cleanup.yaml@main
    secrets: inherit
